services:
  - type: web
    name: mindnest-backend
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        placeholder: "Your PostgreSQL Connection String"
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
